---
id: sysadgirl-backyard
base_name: sysadgirl-backyard
tags:
- Linux
- Comic
- Education
presentation_date: 2017/5/31
version: 2017.05.31
licenses: []
slideshare_id: sysadgirl-backyard
speaker_deck_id: linuxkomandojie-shuo-mangafalsetukurikata
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: 結城洋志
  email: piro.outsider.reflex@gmail.com
  rubygems_user: Piro
  slideshare_user: pirooutsiderreflex
  speaker_deck_user: piroor
